datacite = {
    identifier: {
        identifierType:"",
            content:""
    },
    formats:{
        format:[
            {
                content:""
            }
        ]
    },
    rightsList:{
        rights:[{
            rightsURI:"",
            content:""
        }]
    },
    creators:{
        creator:[
            {
                affiliation:"",
                givenName:"",
                familyName:"",
                creatorName:
                    {
                        nameType:"",
                        content:""
                    },
                nameIdentifier:
                    {
                        nameIdentifierScheme:"",
                        schemeURI:"",
                        content:""
                    }
            }
        ]},
    subjects:{
        subject:[
            {
                schemeURI:"",
                content:"",
                subjectScheme:"",
                xml:""
            }
        ]
    },
    dates:
    {
        date:[
            {
                dateType:"",
                dateInformation:"",
                content:""
            },
        ]
    },
    language:"",
        titles:{
        title:[
            {
                content:"",
                xml:"",
                titleType:""
            }
        ]
    },
    relatedIdentifiers:{
        relatedIdentifier:[
            {
                relationType:"",
                schemeURI:"",
                relatedIdentifierType:"",
                content:"",
                relatedMetadataScheme:""
            },
        ]
    },
    version:"",
        descriptions:
    {
        description:[
            {
                descriptionType:"",
                content:"",
                xml:""}
        ]
    },
    alternateIdentifiers:{
        alternateIdentifier:
            [
                {
                    content:"",
                    alternateIdentifierType:""
                }
            ]
    },
    sizes:{size:[]},
    publisher:"",
        publicationYear:"",
        contributors:{
        contributor:
            [
                {
                    affiliation:"",
                    givenName:"",
                    familyName:"",
                    contributorType:"",
                    contributorName:"",
                    nameIdentifier:{
                        nameIdentifierScheme:"",
                        schemeURI:"",
                        content:""}},
            ]
    },
    fundingReferences:{
        fundingReference:[
            {
                funderName:"",
                funderIdentifier:
                    {
                        funderIdentifierType:"",
                        content:""
                    },
                awardNumber:"",
                awardTitle:""
            },
        ]
    },
    resourceType:{
        resourceTypeGeneral:"",
            content:""
    },
}